### PR TITLE
Refactor: Introduce Includes

### PR DESCRIPTION
**Pull request by gkal19**

### CODE REVIEW

**Comment by alanvitor** [comment]
Thanks for the pull request @gkal19!
But I miss some description of why you did those changes. Readability? Performance?

**Comment by gkal19** [comment]
You're welcome, @alanvitor 

## Motivation

When using ECMAScript arrays, it is commonly desired to determine if the array includes an element. The prevailing pattern for this is

```js
if (arr.indexOf(el) !== -1) {
    ...
}
```

with various other possibilities, e.g. `arr.indexOf(el) >= 0`, or even `~arr.indexOf(el)`.

These patterns exhibit two problems:

- They fail to "say what you mean": instead of asking about whether the array includes an element, you ask what the index of the first occurrence of that element in the array is, and then compare it or bit-twiddle it, to determine the answer to your actual question.
- They fail for `NaN`, as `indexOf` uses Strict Equality Comparison and thus `[NaN].indexOf(NaN) === -1`.

## Proposed Solution

We propose the addition of an `Array.prototype.includes` method, such that the above patterns can be rewritten as

```js
if (arr.includes(el)) {
    ...
}
```

This has almost the same semantics as the above, except that it uses the SameValueZero comparison algorithm instead of Strict Equality Comparison, thus making `[NaN].includes(NaN)` true.

Thus, this proposal solves both problems seen in existing code.

We additionally add a `fromIndex` parameter, similar to `Array.prototype.indexOf` and `String.prototype.includes`, for consistency.

[JSPerf - Includes vs indexOf](https://jsperf.co/includes-vs-indexof)
Information taken from: [Array.prototype.includes](https://github.com/tc39/Array.prototype.includes/)

**Comment by alanvitor** [comment]
Nice! So the motivation is Readability, right?

**Comment by gkal19** [comment]
Yeah, that's the motivation to use `includes`
But if you look for performance indexOf` is more recommended.

Abração para todos da Globo.com :heart:

**Pull request merged**
